"""make_candidate_name_email_nullable

Revision ID: 3b4eeacdd876
Revises: 0aba93fa6783
Create Date: 2026-06-16 19:50:36.462792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b4eeacdd876'
down_revision: Union[str, None] = '0aba93fa6783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('candidates', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('candidates', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
